### PR TITLE
Add missing library definition

### PR DESCRIPTION
**Pull request by fila43**

### CODE REVIEW

**Comment by odubaj** [comment]
looks good, teoretically, we can add the requirement also to Makefile, or remove Makefile completely -> to sustain Makefile and main.fmf have same metadata

**Comment by lukaszachy** [comment]
Pass in TMT, nice.
Re: Makefile - This test will be always run using TMT, right? If so then it is safe to remove Makefile.

**Comment by fila43** [comment]
From my point of view, makefile is necessary, until we will albe to test it in 1minutetip without Makefile.

**Comment by lukaszachy** [comment]
> From my point of view, makefile is necessary, until we will albe to test it in 1minutetip without Makefile.

Good point.

**Pull request merged**
